export const GET_LIST_SERIE = 'GET_LIST_SERIE'
export const POST_SPIRIT = 'POST_SPIRIT'
export const GET_RANDOM_SPIRITS = 'GET_RANDOM_SPIRITS'
export const GET_RESULT_SPIRITS = 'GET_RESULT_SPIRITS'


